server:
  port: 8080

database:
  host: sqlite
  dbname: ./hyun_disk.db

storage:
  path: /app/storage
  mapped_path: /app/storage

jwt:
  secret: hyun_disk_secret_key
  expires_in: 24

admin:
  username: admin
  password: password